# application.properties
spring.application.name=btg-pactual-fondos
server.port=8080

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=btg_fondos

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jp4649561@gmail.com
spring.mail.password=Desepticos19-*/96
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Twilio Configuration (SMS)
twilio.account-sid=tu-account-sid
twilio.auth-token=tu-auth-token
twilio.phone-number=+1234567890

# Logging
logging.level.com.btgpactual.fondos=DEBUG